[package]
name = "lowpass-filter"
description = """
High performance no_std lowpass filter for digital signal processing. A
simple first-order digital filter with a SIMD-accelerated slice API, no
dependencies, no unsafe code, and no allocations.
"""
version = "0.5.0"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2024"
keywords = ["audio", "filter", "digital", "lowpass", "dsp"]
categories = ["multimedia", "no-std", "no-std::no-alloc"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/phip1611/lowpass-filter"
repository = "https://github.com/phip1611/lowpass-filter"
documentation = "https://docs.rs/lowpass-filter/"
rust-version = "1.88"
exclude = [
  ".cargo/",
  ".github/",
  "flake.lock",
  "flake.nix",
  "res/",
  "shell.nix",
  "test/",
]

[dependencies]

[dev-dependencies]
audio-visualizer = "0.5" # to visualize the output
criterion = "0.8"
hound = "3.5"
itertools = "0.15"
spectrum-analyzer = { version = "1.7", default-features = false, features = [] }

[[bench]]
name = "lowpass"
harness = false


# tests, bins, and examples will run faster
[profile.dev]
opt-level = 1
